### ISSUE TITLE
module 'utils' has no attribute 'jload'

### ISSUE THREAD

**Issue by ruio248** [MasterAI-EAM/Darwin#2]
AttributeError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
module 'utils' has no attribute 'jload' 

I have tried multiple versions of utils, but this error keeps occurring.

**Comment by aswinjose89** [comment]
> AttributeError (note: full exception trace is shown but execution is paused at: _run_module_as_main) module 'utils' has no attribute 'jload'
> 
> I have tried multiple versions of utils, but this error keeps occurring.

@ruio248 
Follow the code below
```
import json
with open(data_path, 'r') as file:
    list_data_dict = json.load(file)
```

**Comment by yuweiwan** [comment]
Thanks for your feedback @ruio248 and your answer @aswinjose89 .
We have updated this jload in https://github.com/MasterAI-EAM/Darwin/blob/main/utils.py 
Welcome to continue following us and providing feedback & suggestions. We are in the process of developing DARWIN 2.0.
