### ISSUE TITLE
Problem loading pretrained checkpoints

### ISSUE THREAD

**Issue by fedeotto** [MasterAI-EAM/Darwin#6]
Hi everyone, I've attempted multiple times to download the `darwin-7b` folder, but each time I've faced an issue with the `pytorch_model-00001-of-00003.bin` file. Whenever I try to load the checkpoint as demonstrated in the `inference.ipynb` example, I encounter the following error:

```
...

RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted

During handling of the above exception, another exception occurred:
...

OSError: Unable to load weights from pytorch checkpoint file for 'darwin-7b/pytorch_model-00001-of-00003.bin' at 'darwin-7b/pytorch_model-00001-of-00003.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```
As I said, I have tried downloading the file multiple times and the process always terminates smoothly. Not sure whether someone else has encountered the same issue. Thanks

**Comment by 0xTong** [comment]
@yuweiwan could you sovled that

**Comment by yuweiwan** [comment]
@fedeotto Thank you for your question. I have checked this file and will change a new one soon.

**Comment by fedeotto** [comment]
Hi, many thanks for your answer, in the end the issue was on my side, as manually downloading the checkpoint resulted in having corrupted files for some reason, most likely due to connection issues.

I have then downloaded them using `!gdown` as shown in `inference.ipynb` and was able to make it work :)
